name: term_summary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/profile.png
    - lib/assets/about.png
    - lib/assets/experience.png
    - lib/assets/verbasense.png
    - lib/assets/capacitor.png
    - lib/assets/icecream.png
